version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: unshorten-it-backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - REQUEST_TIMEOUT=15.0
      - ALLOW_ORIGINS=http://localhost:8080,http://localhost:3000,http://unshorten.bitmaskers.in,https://unshorten.bitmaskers.in
      - REDIS_URL=redis://redis:6379/1
      - CACHE_EXPIRE_SECONDS=86400
    # Use environment variables for the backend if needed

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      # Change this URL if deploying to a remote server
      API_BASE_URL: http://localhost:8000
    container_name: unshorten-it-frontend
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - backend

  redis:
    image: redis:alpine
    container_name: unshorten-it-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data:
