package `in`.bitmaskers.unshortenit.ui.theme

import androidx.compose.ui.graphics.Color

// Light Colors
val md_theme_light_primary = Color(0xFF4F46E5)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFEEF2FF)
val md_theme_light_onPrimaryContainer = Color(0xFF312E81)
val md_theme_light_secondary = Color(0xFF6366F1)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE0E7FF)
val md_theme_light_onSecondaryContainer = Color(0xFF1E1B4B)
val md_theme_light_tertiary = Color(0xFF7C3AED)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFF3E8FF)
val md_theme_light_onTertiaryContainer = Color(0xFF581C87)
val md_theme_light_error = Color(0xFFDC2626)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_background = Color(0xFFF9FAFB)
val md_theme_light_onBackground = Color(0xFF0F172A)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF0F172A)
val md_theme_light_surfaceVariant = Color(0xFFF1F5F9)
val md_theme_light_onSurfaceVariant = Color(0xFF64748B)
val md_theme_light_outline = Color(0xFFCBD5E1)

// Dark Colors
val md_theme_dark_primary = Color(0xFF818CF8)
val md_theme_dark_onPrimary = Color(0xFF1E1B4B)
val md_theme_dark_primaryContainer = Color(0xFF3730A3)
val md_theme_dark_onPrimaryContainer = Color(0xFFE0E7FF)
val md_theme_dark_secondary = Color(0xFFA5B4FC)
val md_theme_dark_onSecondary = Color(0xFF1E1B4B)
val md_theme_dark_secondaryContainer = Color(0xFF312E81)
val md_theme_dark_onSecondaryContainer = Color(0xFFE0E7FF)
val md_theme_dark_tertiary = Color(0xFFC084FC)
val md_theme_dark_onTertiary = Color(0xFF3B0764)
val md_theme_dark_tertiaryContainer = Color(0xFF581C87)
val md_theme_dark_onTertiaryContainer = Color(0xFFF3E8FF)
val md_theme_dark_error = Color(0xFFF87171)
val md_theme_dark_onError = Color(0xFF450A0A)
val md_theme_dark_background = Color(0xFF0B0F19)
val md_theme_dark_onBackground = Color(0xFFF8FAFC)
val md_theme_dark_surface = Color(0xFF151C2C)
val md_theme_dark_onSurface = Color(0xFFF8FAFC)
val md_theme_dark_surfaceVariant = Color(0xFF1E293B)
val md_theme_dark_onSurfaceVariant = Color(0xFF94A3B8)
val md_theme_dark_outline = Color(0xFF334155)